# Generated by Django 5.0.2 on 2024-02-29 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollmentquestionnaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=150, verbose_name='Gender')),
                ('has_understood_purpose_of_the_study', models.BooleanField(max_length=150, verbose_name='Subject has understood purpose of the study')),
                ('has_understood_risks', models.BooleanField(max_length=150, verbose_name='Subject ha understood the risks of participating in this study')),
                ('has_understood_potential_benefits', models.BooleanField(max_length=150, verbose_name='Subject has understood potential benefits of participating in the study')),
                ('marital_status', models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed')], max_length=150, verbose_name="Subject's marital status")),
                ('number_of_wives', models.IntegerField(verbose_name='')),
                ('currently_live_with', models.CharField(choices=[('ALONE', 'Alone'), ('PARTNER', 'Partner'), ('SIBLING(S)', 'Sibling(s)'), ('OTHER', 'Other'), ('DO NOT WANT TO ANSWER', 'Do not want to answer')], max_length=150, verbose_name='Who do you currently live with')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollmentquestionnaire.enrollmentchecklist', verbose_name='Subject identifier')),
            ],
        ),
    ]
