# Generated by Django 5.0.2 on 2024-02-29 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollmentquestionnaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectEmployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_working', models.BooleanField(verbose_name='Are you currently working?')),
                ('work_type', models.CharField(blank=True, choices=[('OCCASIONAL OR CASUAL EMPLOYMENT (PIECE JOB)', 'Occasional or Casual employment (piece job)'), ('SEASONAL EMPLOYMENT', 'Seasonal employment'), ('FORMAL WAGE EMPLOYMENT (FULL-TIME)', 'Formal wage employment (full-time)'), ('FORMAL WAGE EMPLOYMENT (PART-TIME)', 'Formal wage employment (part-time)'), ('SELF-EMPLOYED IN AGRICULTURE', 'Self-employed in agriculture'), ('SELF-EMPLOYED MAKING MONEY (FULL-TIME)', 'Self-employed making money (full-time)'), ('SELF-EMPLOYED MAKING MONEY (PART-TIME)', 'Self-employed making money (part-time)'), ('OTHER', 'Other'), ('DO NOT WANT TO ANSWER', 'Do not want to answer')], max_length=150, null=True, verbose_name='In your main job what type of work do you do?')),
                ('occupation', models.CharField(blank=True, choices=[('FARMER (OWN LAND)', 'Farmer (own land)'), ('FARM WORK EMPLOYERS LAND', 'Farm work on employers land'), ('DOMESTIC WORKER', 'Domestic worker'), ('WORK IN BAR/HOTEL/GUEST HOUSE/ENTERTAINMENT VENUE', 'Work in bar/hotel/guest house/entertainment venue'), ('FISHING', 'Fishing'), ('MINING', 'Mining'), ('TOURISM/GAME PARKS', 'Tourism/game parks'), ('WORKING IN SHOP/SMALL BUSINESS', 'Working in shop/small business'), ('INFORMAL SELLING', 'Informal selling'), ('COMMERCIAL SEX WORK', 'Commercial sex work'), ('TRANSPORT (TRUCKER/TAXI DRIVER)', 'Transport (trucker/taxi driver)'), ('FACTORY WORKER', 'Factory worker'), ('GUARD (SECURITY COMPANY)', 'Guard (security company)'), ('POLICE/SOLDIER', 'Police/Soldier'), ('CLERICAL AND OFFICE WORK', 'Clerical and office work'), ('GOVERNMENT WORKER', 'Government worker'), ('TEACHER', 'Teacher'), ('HEALTH CARE WORKER', 'Health care worker'), ('OTHER PROFESSIONAL', 'Other professional'), ('OTHER', 'Other'), ('DO NOT WANT TO ANSWER', 'Do not want to answer')], max_length=150, null=True, verbose_name='Describe the work that you do or did in your most recent job. If you have more than one profession, choose the one you spend the most time doing. ')),
                ('income', models.CharField(blank=True, choices=[('NONE', 'None'), ('1-199 PULA', '1-199 pula'), ('200-499 PULA', '200-499 pula'), ('500-999 PULA', '500-999 pula'), ('1000-4999 PULA', '1000-4999 pula'), ('5000-10000 PULA', '5000-10000 pula'), ('MORE THAN 10000 PULA', 'More than 10000 pula'), ('DO NOT WANT TO ANSWER', 'Do not want to answer')], max_length=150, null=True, verbose_name='In the past month, how much money did you earn from work you did or received in payment?')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollmentquestionnaire.enrollmentchecklist', verbose_name='Subject identifier')),
            ],
        ),
    ]
