# Generated by Django 5.0.2 on 2024-02-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentChecklist',
            fields=[
                ('subject_id', models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='Subject identifier')),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=6, verbose_name='Gender')),
                ('is_botswana_citizen', models.BooleanField(default=False, max_length=150, verbose_name='Are you a Botswana citizen?')),
                ('is_married_to_botswana_citizen', models.BooleanField(blank=True, default=False, max_length=150, null=True, verbose_name='If not a citizen, are you legally married to a Botswana Citizen?')),
                ('has_marriage_certificate', models.BooleanField(blank=True, default=False, max_length=150, null=True, verbose_name='Has the participant produced the marriage certificate, as proof?')),
                ('is_literate', models.BooleanField(default=False, verbose_name='Is the participant LITERATE?')),
                ('has_literate_witness', models.BooleanField(blank=True, default=False, max_length=150, null=True, verbose_name='If ILLITERATE, is there a LITERATE witness available? ')),
                ('is_minor', models.BooleanField(default=False, verbose_name='Is the participant a minor?')),
                ('guardian_available', models.BooleanField(blank=True, default=False, max_length=150, null=True, verbose_name='If the participant is a minor, is their guardian available')),
            ],
        ),
    ]
