# Generated by Django 5.0.2 on 2024-02-29 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollmentquestionnaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityInvolvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('involvement_rate', models.CharField(choices=[('VERY ACTIVE', 'Very active'), ('SOMEWHAT ACTIVE', 'Somewhat active'), ('NOT ACTIVE AT ALL', 'Not active at all'), ('DO NOT WANT TO ANSWER', 'Do not want to answer')], max_length=150, verbose_name='How active are you in community activities such as burial society, Motshelo, Syndicate, PTA, VDC(Village Development Committee), Mophato and development of the community that surrounds you?')),
                ('previously_voted', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('NOT APPLICABLE', 'Not applicable'), ('DO NOT WANT TO ANSWER', 'Do not want to answer')], max_length=150, verbose_name='Did you vote in the last local government election?')),
                ('major_problems', models.CharField(choices=[('HIV/AIDS', 'HIV/AIDS'), ('SCHOOLS', 'Schools'), ('SEWER', 'Sewer'), ('UNEMPLOYMENT', 'Unemployment'), ('ROADS', 'Roads'), ('WATER', 'Water'), ('HOUSING', 'Housing'), ('MALARIA', 'Malaria')], max_length=150, verbose_name='What are the major problems in this neighborhood?')),
                ('adults_solving_problems', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ("DON'T KNOW", "Don't know"), ("DON'T WANT TO ANSWER", "Don't want to answer")], max_length=150, verbose_name='If there is a problem in this neighborhood, do the adults work together in solving it?')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollmentquestionnaire.enrollmentchecklist', verbose_name='Subject identifier')),
            ],
        ),
    ]
